### ISSUE TITLE
Fork Environment Code and Language are lost when set to Docker

### ISSUE THREAD

**Issue by laugimethods** [ow2-proactive/studio#576] opened 2018-07-31 14:14 UTC
After switching back and forth to the scheduler console, the code and the language of the Fork Environment are visually lost (the task still run fine still following to the original code).

Related to https://github.com/ow2-proactive/studio/issues/98 (?)

![screen shot 2018-07-31 at 10 13 44](https://user-images.githubusercontent.com/16766201/43465027-6eeed300-94aa-11e8-8757-83f187e712c0.png)

**Comment by laugimethods** [comment] 2018-07-31 14:25
Actually, the code is visually lost as soon as the task is no more selected.

**Comment by fviale** [comment] 2018-07-31 14:44
Thank you laurent for this bug report. I recently redesigned some parts of the studio interface and probably introduced a regression. I will look into this asap.

**Comment by laugimethods** [comment] 2018-07-31 14:44
I guess that the following code is executed only once, and its result is not save by the studio (but the scheduler).
https://github.com/ow2-proactive/studio/blob/4e7e8d3db53f374b92a070f9f1bb0a333e134422/app/scripts/proactive/view/TaskView.js#L172

**Comment by fviale** [comment] 2018-07-31 14:45
you are right that the reason is because, the workflow is not saved automatically in this context. Could you check that the issue disappears if you manually hit "save" ?

**Comment by laugimethods** [comment] 2018-07-31 14:46
"Save" doesn't solve the issue...

**Comment by fviale** [comment] 2018-08-01 11:44
fixed by c48ddc2

**Closed** 2018-08-01 11:44 UTC
Labels: resolution:fixed, severity:minor, type:bug
